#!/bin/bash
#
# $Id$
#
# LINUX JAR CREATION SCRIPT FOR EBLA

# DELETE ANY EXISTING RELEASE JARS
rm -r ./release_jars

# DELETE ANY TMP FILES IN CURRENT DIRECTORY
rm *~

# MAKE DIRECTORIES NEEDED FOR JARS
mkdir ./release_jars
mkdir ./release_jars/bin
mkdir ./release_jars/database
mkdir ./release_jars/database/csv_data
mkdir ./release_jars/docs
mkdir ./release_jars/experiences
mkdir ./release_jars/jars
mkdir ./release_jars/src
mkdir ./release_jars/src/com
mkdir ./release_jars/src/com/greatmindsworking
mkdir ./release_jars/src/com/greatmindsworking/EBLA
mkdir ./release_jars/src/com/greatmindsworking/EBLA/Interfaces
mkdir ./release_jars/src/com/greatmindsworking/utils
mkdir ./release_jars/src/com/greatmindsworking/EDISON
mkdir ./release_jars/src/com/greatmindsworking/EDISON/segm
#mkdir ./release_jars/src/com/greatmindsworking/EDISON/utils

# RECOMPILE EBLA
javac -source 1.6 -target 1.6 -Xlint -d ./release_jars/bin -classpath .:./jars/h2-1.3.155.jar:./jars/jmf.jar:./jars/swingset-bin.jar ./src/com/greatmindsworking/utils/*.java ./src/com/greatmindsworking/EDISON/segm/*.java ./src/com/greatmindsworking/EBLA/*.java ./src/com/greatmindsworking/EBLA/Interfaces/*.java

# REBUILD JAVADOCS
javadoc -d ./release_jars/docs -classpath .:./jars/h2-1.3.155.jar:./jars/jmf.jar:./jars/swingset-bin.jar ./src/com/greatmindsworking/utils/*.java ./src/com/greatmindsworking/EBLA/*.java ./src/com/greatmindsworking/EBLA/Interfaces/*.java ./src/com/greatmindsworking/EDISON/segm/*.java

# COPY SOURCE CODE
cp ./src/com/greatmindsworking/EBLA/*.java ./release_jars/src/com/greatmindsworking/EBLA/
rm ./release_jars/src/com/greatmindsworking/EBLA/*.java~
cp ./src/com/greatmindsworking/EBLA/Interfaces/*.java ./release_jars/src/com/greatmindsworking/EBLA/Interfaces/
rm ./release_jars/src/com/greatmindsworking/EBLA/Interfaces/*.java~
cp ./src/com/greatmindsworking/utils/*.java ./release_jars/src/com/greatmindsworking/utils/
rm ./release_jars/src/com/greatmindsworking/utils/*.java~
cp ./src/com/greatmindsworking/EDISON/segm/*.java ./release_jars/src/com/greatmindsworking/EDISON/segm/
rm ./release_jars/src/com/greatmindsworking/EDISON/segm/*.java~
#cp ./src/com/greatmindsworking/EDISON/utils/*.java ./release_jars/src/com/greatmindsworking/EDISON/utils/
#rm ./release_jars/src/com/greatmindsworking/EDISON/utils/*.java~

# COPY DATABASE FILES
cp ./database/*.sql ./release_jars/database/
cp ./database/csv_data/*.csv ./release_jars/database/csv_data/

# COPY EXPERIENCES
cp ./experiences/ball_down1.avi ./release_jars/experiences/
cp ./experiences/ball_slide1.avi ./release_jars/experiences/
cp ./experiences/ball_touch1.avi ./release_jars/experiences/
cp ./experiences/ball_up1.avi ./release_jars/experiences/
cp ./experiences/cube_down1.avi ./release_jars/experiences/
cp ./experiences/cube_slide1.avi ./release_jars/experiences/
cp ./experiences/cube_touch1.avi ./release_jars/experiences/
cp ./experiences/cube_up1.avi ./release_jars/experiences/

# COPY JARS
cp ./jars/swingset-bin.jar ./release_jars/jars/
cp ./jars/jars/h2-1.3.155.jar ./release_jars/jars/

# BUILD BIN JAR
jar -cvf ./release_jars/ebla-bin_current.jar -C ./release_jars bin -C ./release_jars experiences -C ./release_jars jars changelog.txt linrun readme.txt winrun.bat

# BUILD JAVADOC JAR
jar -cvf ./release_jars/ebla-docs_current.jar -C ./release_jars docs changelog.txt readme.txt

# BUILD SOURCE JAR
jar -cvf ./release_jars/ebla-src_current.jar -C ./release_jars src -C ./release_jars database -C ./release_jars experiences -C ./release_jars jars changelog.txt lin* readme.txt win*
