#!/bin/bash
#
# $Id$
#
# LINUX COMPILATION SCRIPT FOR EBLA
#
# DELETE ANY EXISTING .class FILES AND RE-COMPILE ALL .java FILES FOR EBLA
#
rm ./com/greatmindsworking/EBLA/*.class
rm ./com/greatmindsworking/EBLA/Interfaces/*.class
rm ./com/greatmindsworking/EDISON/segm/*.class
javac -classpath .;./jars/rowset.jar;./jars/pg73jdbc3.jar;./jars/jmf.jar;./jars/swingSet.jar;./jars/utils.jar com/greatmindsworking/EBLA/Interfaces/EBLAGui.java