#!/bin/bash
#
# $Id$
#
# LINUX JAVADOC GENERATION SCRIPT FOR EBLA
#
rm -r ./javadoc
mkdir ./javadoc
javadoc -d javadoc -classpath .:./jars/h2-1.3.154.jar:./jars/jmf.jar:./jars/swingset-bin.jar ./src/com/greatmindsworking/utils/*.java ./src/com/greatmindsworking/EBLA/*.java ./src/com/greatmindsworking/EBLA/Interfaces/*.java ./src/com/greatmindsworking/EDISON/segm/*.java