#!/bin/bash
#
# $Id$
#
# LINUX EXECUTION SCRIPT FOR EBLA
#
java -classpath .;./jars/rowset.jar;./jars/pg73jdbc3.jar;./jars/jmf.jar;./jars/swingSet.jar;./jars/utils.jar com.greatmindsworking.EBLA.Interfaces.EBLAGui