#!/bin/bash
#
# $Id$
#
# LINUX JAVADOC GENERATION SCRIPT FOR EBLA
#
cd ..
rm -r ./docs
mkdir ./docs
javadoc -d docs -classpath .:./jars/h2-1.4.177.jar:./jars/jmf.jar:./jars/swingset-bin.jar ./src/com/greatmindsworking/utils/*.java ./src/com/greatmindsworking/EBLA/*.java ./src/com/greatmindsworking/EBLA/Interfaces/*.java ./src/com/greatmindsworking/EDISON/segm/*.java